defaults:
  - task: task
  - data_splitting: data_splitting
  - model: model
  - training: training
  - test: test
  - _self_

device: "cuda:0"
rnd_seed: 0
create_orfs: False
results_directory: "results"
database:
  metadata_file: "database_modified/metadata.tsv"
  repertoiresdata_path: "database_modified/orfs"